name: Build and Deploy Staging

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE: ghcr.io/${{ github.repository_owner }}/drug-repurposing-backend
  FRONTEND_IMAGE: ghcr.io/${{ github.repository_owner }}/drug-repurposing-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./python-backend
          push: true
          tags: |
            ${{ env.BACKEND_IMAGE }}:latest
            ${{ env.BACKEND_IMAGE }}:${{ github.sha }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./web-app
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE }}:latest
            ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}

  deploy-placeholder:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Staging deployment placeholder
        run: |
          echo "Images published:"
          echo "  Backend  -> ${{ env.BACKEND_IMAGE }}:${{ github.sha }}"
          echo "  Frontend -> ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}"
          echo "Add kubectl/helm/compose commands here to roll out staging."
